name: moekyawaung_flutter_pro_max_v5
description: Flutter Pro Max V5 Ultimate - 1000+ Particles | AI Animations | Multi-Language
publish_to: 'none'
version: 6.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  google_fonts: ^6.1.0
  flutter_animate: ^4.3.0
  animate_do: ^3.1.2
  url_launcher: ^6.2.1
  font_awesome_flutter: ^10.6.0
  smooth_page_indicator: ^1.1.0
  glassmorphism: ^3.0.0
  flutter_tilt_card: ^1.0.3
  flutter_native_splash: ^2.3.0
  package_info_plus: ^5.0.0
  share_plus: ^7.0.0
  wakelock_plus: ^1.1.0
  flutter_localizations: ^0.0.1
  intl: ^0.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
